apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: alist
  name: alist
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: alist
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/k8s-test-default: "true"
        io.kompose.service: alist
    spec:
      containers:
        - env:
            - name: PGID
              value: "0"
            - name: PUID
              value: "0"
            - name: UMASK
              value: "022"
          image: xhofe/alist:latest
          name: alist
          ports:
            - containerPort: 5244
              hostPort: 5244
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/alist/data
              name: alist-claim0
      restartPolicy: Always
      volumes:
        - name: alist-claim0
          persistentVolumeClaim:
            claimName: alist-claim0
