apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: halodb
  name: halodb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: halodb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/test-halo-halo-network: "true"
        io.kompose.service: halodb
    spec:
      containers:
        - env:
            - name: PGUSER
              value: halo
            - name: POSTGRES_DB
              value: halo
            - name: POSTGRES_PASSWORD
              value: openpostgresql
            - name: POSTGRES_USER
              value: halo
          image: postgres:15.4
          livenessProbe:
            exec:
              command:
                - pg_isready
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: halodb
          ports:
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: halodb-claim0
      restartPolicy: Always
      volumes:
        - name: halodb-claim0
          persistentVolumeClaim:
            claimName: halodb-claim0
